@api= http://localhost:8000/api/pedidos

GET {{api}}

###
GET {{api}}/6

###
POST {{api}}
Content-Type: application/json

{
  "idpedi": 5,
  "canped": 10
}

###
DELETE {{api}}/6

###
PUT {{api}}/5
Content-Type: application/json

{
  "canped": 101,
  "idclie": 7,
  "userid": "pp53",
  "nomcli": "FRANCISCO PEREZ",
  "emacli": "francisco.perez@bizkaia.eus",
  "idclie": 7
}